// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJhZUCZO3yDoAX6r9lSrd3lIDbQKTwWw',
    appId: '1:600695514767:web:81d826b5df3a3981bcb2fa',
    messagingSenderId: '600695514767',
    projectId: 'newapp-1f568',
    authDomain: 'newapp-1f568.firebaseapp.com',
    storageBucket: 'newapp-1f568.firebasestorage.app',
    measurementId: 'G-0K03LLV9BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3YKaWGqJhSnA8PQf4BnoNgNXarukKH4',
    appId: '1:600695514767:android:1267a4fc96bbea3bbcb2fa',
    messagingSenderId: '600695514767',
    projectId: 'newapp-1f568',
    storageBucket: 'newapp-1f568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc75VM-w5gzKfxBh5jafVXLxkaw3CscfA',
    appId: '1:600695514767:ios:b89a08776a5147f1bcb2fa',
    messagingSenderId: '600695514767',
    projectId: 'newapp-1f568',
    storageBucket: 'newapp-1f568.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc75VM-w5gzKfxBh5jafVXLxkaw3CscfA',
    appId: '1:600695514767:ios:b89a08776a5147f1bcb2fa',
    messagingSenderId: '600695514767',
    projectId: 'newapp-1f568',
    storageBucket: 'newapp-1f568.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLJhZUCZO3yDoAX6r9lSrd3lIDbQKTwWw',
    appId: '1:600695514767:web:5ab900d06842a80bbcb2fa',
    messagingSenderId: '600695514767',
    projectId: 'newapp-1f568',
    authDomain: 'newapp-1f568.firebaseapp.com',
    storageBucket: 'newapp-1f568.firebasestorage.app',
    measurementId: 'G-4JRY3E3MVV',
  );
}
