// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmsUVvJEVUJ_CqgE7bp9QwxIwvF0k9Sxs',
    appId: '1:535857115321:web:9e3d71678af349c760ab68',
    messagingSenderId: '535857115321',
    projectId: 'final-743da',
    authDomain: 'final-743da.firebaseapp.com',
    storageBucket: 'final-743da.firebasestorage.app',
    measurementId: 'G-EGYYDPBCQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYy_96VDM-9jw1W60lKwWxsplojgtbhn8',
    appId: '1:535857115321:android:d2cd7517addf442e60ab68',
    messagingSenderId: '535857115321',
    projectId: 'final-743da',
    storageBucket: 'final-743da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3SSlJz9XcVK2jyx3aQgl-IYtZ6Sbi5Rg',
    appId: '1:535857115321:ios:dfe2f7ac84d32b7f60ab68',
    messagingSenderId: '535857115321',
    projectId: 'final-743da',
    storageBucket: 'final-743da.firebasestorage.app',
    iosClientId: '535857115321-t1cil3far5j9857lps71d4frotnhocp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3SSlJz9XcVK2jyx3aQgl-IYtZ6Sbi5Rg',
    appId: '1:535857115321:ios:dfe2f7ac84d32b7f60ab68',
    messagingSenderId: '535857115321',
    projectId: 'final-743da',
    storageBucket: 'final-743da.firebasestorage.app',
    iosClientId: '535857115321-t1cil3far5j9857lps71d4frotnhocp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmsUVvJEVUJ_CqgE7bp9QwxIwvF0k9Sxs',
    appId: '1:535857115321:web:bdb6704fc56fedda60ab68',
    messagingSenderId: '535857115321',
    projectId: 'final-743da',
    authDomain: 'final-743da.firebaseapp.com',
    storageBucket: 'final-743da.firebasestorage.app',
    measurementId: 'G-TMESE1VF5S',
  );

}